<?xml version="1.0" ?>
<sld:StyledLayerDescriptor version="1.0.0" xmlns="http://www.opengis.net/sld" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" xmlns:sld="http://www.opengis.net/sld">
    <sld:UserLayer>
        <sld:LayerFeatureConstraints>
            <sld:FeatureTypeConstraint/>
        </sld:LayerFeatureConstraints>
        <sld:UserStyle>
            <sld:Name>World_DEM</sld:Name>
            <sld:Description>Generated by SLD4raster - https://cbsuygulama.wordpress.com/sld4raster</sld:Description>
            <sld:Title/>
            <sld:FeatureTypeStyle>
                <sld:Name/>
                <sld:Rule>
                    <sld:RasterSymbolizer>
                        <sld:Geometry>
                            <ogc:PropertyName>grid</ogc:PropertyName>
                        </sld:Geometry>
                        <sld:Opacity>1</sld:Opacity>
                        <sld:ColorMap>
                            <sld:ColorMapEntry color="#aeefd5" label="-154" opacity="1.0" quantity="-154"/>
                            <sld:ColorMapEntry color="#aff0d3" label="7" opacity="1.0" quantity="7"/>
                            <sld:ColorMapEntry color="#b0f2d0" label="7" opacity="1.0" quantity="7"/>
                            <sld:ColorMapEntry color="#b0f2ca" label="16" opacity="1.0" quantity="16"/>
                            <sld:ColorMapEntry color="#b1f2c4" label="16" opacity="1.0" quantity="16"/>
                            <sld:ColorMapEntry color="#b0f3be" label="25" opacity="1.0" quantity="25"/>
                            <sld:ColorMapEntry color="#b0f5ba" label="34" opacity="1.0" quantity="34"/>
                            <sld:ColorMapEntry color="#b2f6b5" label="42" opacity="1.0" quantity="42"/>
                            <sld:ColorMapEntry color="#b6f7b2" label="42" opacity="1.0" quantity="42"/>
                            <sld:ColorMapEntry color="#bbf7b2" label="51" opacity="1.0" quantity="51"/>
                            <sld:ColorMapEntry color="#c1f8b2" label="60" opacity="1.0" quantity="60"/>
                            <sld:ColorMapEntry color="#c7f9b2" label="69" opacity="1.0" quantity="69"/>
                            <sld:ColorMapEntry color="#cdfab2" label="78" opacity="1.0" quantity="78"/>
                            <sld:ColorMapEntry color="#d3fab1" label="87" opacity="1.0" quantity="87"/>
                            <sld:ColorMapEntry color="#dafbb2" label="96" opacity="1.0" quantity="96"/>
                            <sld:ColorMapEntry color="#e1fcb2" label="105" opacity="1.0" quantity="105"/>
                            <sld:ColorMapEntry color="#e8fcb2" label="114" opacity="1.0" quantity="114"/>
                            <sld:ColorMapEntry color="#effcb3" label="123" opacity="1.0" quantity="123"/>
                            <sld:ColorMapEntry color="#f6fcb3" label="132" opacity="1.0" quantity="132"/>
                            <sld:ColorMapEntry color="#fafcb1" label="132" opacity="1.0" quantity="132"/>
                            <sld:ColorMapEntry color="#f7f9ab" label="140" opacity="1.0" quantity="140"/>
                            <sld:ColorMapEntry color="#edf4a1" label="149" opacity="1.0" quantity="149"/>
                            <sld:ColorMapEntry color="#e1f096" label="158" opacity="1.0" quantity="158"/>
                            <sld:ColorMapEntry color="#d3ea8a" label="167" opacity="1.0" quantity="167"/>
                            <sld:ColorMapEntry color="#c4e37e" label="176" opacity="1.0" quantity="176"/>
                            <sld:ColorMapEntry color="#b6dd74" label="185" opacity="1.0" quantity="185"/>
                            <sld:ColorMapEntry color="#a7d76a" label="185" opacity="1.0" quantity="185"/>
                            <sld:ColorMapEntry color="#98d260" label="194" opacity="1.0" quantity="194"/>
                            <sld:ColorMapEntry color="#89cc58" label="203" opacity="1.0" quantity="203"/>
                            <sld:ColorMapEntry color="#7ac650" label="212" opacity="1.0" quantity="212"/>
                            <sld:ColorMapEntry color="#6bc148" label="221" opacity="1.0" quantity="221"/>
                            <sld:ColorMapEntry color="#5abb40" label="230" opacity="1.0" quantity="230"/>
                            <sld:ColorMapEntry color="#4ab537" label="238" opacity="1.0" quantity="238"/>
                            <sld:ColorMapEntry color="#3baf30" label="256" opacity="1.0" quantity="256"/>
                            <sld:ColorMapEntry color="#2eaa2b" label="265" opacity="1.0" quantity="265"/>
                            <sld:ColorMapEntry color="#24a42a" label="274" opacity="1.0" quantity="274"/>
                            <sld:ColorMapEntry color="#1c9f2b" label="283" opacity="1.0" quantity="283"/>
                            <sld:ColorMapEntry color="#16992e" label="292" opacity="1.0" quantity="292"/>
                            <sld:ColorMapEntry color="#119331" label="310" opacity="1.0" quantity="310"/>
                            <sld:ColorMapEntry color="#0c8d35" label="319" opacity="1.0" quantity="319"/>
                            <sld:ColorMapEntry color="#088839" label="328" opacity="1.0" quantity="328"/>
                            <sld:ColorMapEntry color="#08833d" label="336" opacity="1.0" quantity="336"/>
                            <sld:ColorMapEntry color="#0f823f" label="345" opacity="1.0" quantity="345"/>
                            <sld:ColorMapEntry color="#1c833e" label="354" opacity="1.0" quantity="354"/>
                            <sld:ColorMapEntry color="#2b853c" label="372" opacity="1.0" quantity="372"/>
                            <sld:ColorMapEntry color="#37893b" label="381" opacity="1.0" quantity="381"/>
                            <sld:ColorMapEntry color="#438d3b" label="390" opacity="1.0" quantity="390"/>
                            <sld:ColorMapEntry color="#4f8f3a" label="399" opacity="1.0" quantity="399"/>
                            <sld:ColorMapEntry color="#5b9337" label="417" opacity="1.0" quantity="417"/>
                            <sld:ColorMapEntry color="#679535" label="426" opacity="1.0" quantity="426"/>
                            <sld:ColorMapEntry color="#719733" label="434" opacity="1.0" quantity="434"/>
                            <sld:ColorMapEntry color="#7b9b31" label="452" opacity="1.0" quantity="452"/>
                            <sld:ColorMapEntry color="#839e2f" label="461" opacity="1.0" quantity="461"/>
                            <sld:ColorMapEntry color="#8da12d" label="470" opacity="1.0" quantity="470"/>
                            <sld:ColorMapEntry color="#96a32a" label="488" opacity="1.0" quantity="488"/>
                            <sld:ColorMapEntry color="#a0a528" label="497" opacity="1.0" quantity="497"/>
                            <sld:ColorMapEntry color="#aaa826" label="506" opacity="1.0" quantity="506"/>
                            <sld:ColorMapEntry color="#b4ab23" label="524" opacity="1.0" quantity="524"/>
                            <sld:ColorMapEntry color="#bfae20" label="532" opacity="1.0" quantity="532"/>
                            <sld:ColorMapEntry color="#c9b11d" label="550" opacity="1.0" quantity="550"/>
                            <sld:ColorMapEntry color="#d4b21a" label="568" opacity="1.0" quantity="568"/>
                            <sld:ColorMapEntry color="#deb416" label="577" opacity="1.0" quantity="577"/>
                            <sld:ColorMapEntry color="#e9b511" label="595" opacity="1.0" quantity="595"/>
                            <sld:ColorMapEntry color="#f2b60b" label="613" opacity="1.0" quantity="613"/>
                            <sld:ColorMapEntry color="#f7b406" label="622" opacity="1.0" quantity="622"/>
                            <sld:ColorMapEntry color="#f7ac03" label="639" opacity="1.0" quantity="639"/>
                            <sld:ColorMapEntry color="#f2a102" label="657" opacity="1.0" quantity="657"/>
                            <sld:ColorMapEntry color="#ec9602" label="675" opacity="1.0" quantity="675"/>
                            <sld:ColorMapEntry color="#e68b02" label="693" opacity="1.0" quantity="693"/>
                            <sld:ColorMapEntry color="#e07f02" label="711" opacity="1.0" quantity="711"/>
                            <sld:ColorMapEntry color="#da7502" label="720" opacity="1.0" quantity="720"/>
                            <sld:ColorMapEntry color="#d66b02" label="737" opacity="1.0" quantity="737"/>
                            <sld:ColorMapEntry color="#d16102" label="755" opacity="1.0" quantity="755"/>
                            <sld:ColorMapEntry color="#cb5802" label="773" opacity="1.0" quantity="773"/>
                            <sld:ColorMapEntry color="#c44f02" label="791" opacity="1.0" quantity="791"/>
                            <sld:ColorMapEntry color="#bd4602" label="809" opacity="1.0" quantity="809"/>
                            <sld:ColorMapEntry color="#b73e02" label="826" opacity="1.0" quantity="826"/>
                            <sld:ColorMapEntry color="#b13502" label="844" opacity="1.0" quantity="844"/>
                            <sld:ColorMapEntry color="#ac2d02" label="862" opacity="1.0" quantity="862"/>
                            <sld:ColorMapEntry color="#a62602" label="880" opacity="1.0" quantity="880"/>
                            <sld:ColorMapEntry color="#a02002" label="898" opacity="1.0" quantity="898"/>
                            <sld:ColorMapEntry color="#9a1a02" label="916" opacity="1.0" quantity="916"/>
                            <sld:ColorMapEntry color="#941401" label="933" opacity="1.0" quantity="933"/>
                            <sld:ColorMapEntry color="#8f0f01" label="951" opacity="1.0" quantity="951"/>
                            <sld:ColorMapEntry color="#8a0a00" label="969" opacity="1.0" quantity="969"/>
                            <sld:ColorMapEntry color="#840600" label="987" opacity="1.0" quantity="987"/>
                            <sld:ColorMapEntry color="#7f0400" label="1005" opacity="1.0" quantity="1005"/>
                            <sld:ColorMapEntry color="#7b0601" label="1014" opacity="1.0" quantity="1014"/>
                            <sld:ColorMapEntry color="#780b02" label="1031" opacity="1.0" quantity="1031"/>
                            <sld:ColorMapEntry color="#760e02" label="1049" opacity="1.0" quantity="1049"/>
                            <sld:ColorMapEntry color="#751103" label="1067" opacity="1.0" quantity="1067"/>
                            <sld:ColorMapEntry color="#751304" label="1085" opacity="1.0" quantity="1085"/>
                            <sld:ColorMapEntry color="#751404" label="1103" opacity="1.0" quantity="1103"/>
                            <sld:ColorMapEntry color="#741504" label="1120" opacity="1.0" quantity="1120"/>
                            <sld:ColorMapEntry color="#741704" label="1138" opacity="1.0" quantity="1138"/>
                            <sld:ColorMapEntry color="#731905" label="1156" opacity="1.0" quantity="1156"/>
                            <sld:ColorMapEntry color="#721c06" label="1174" opacity="1.0" quantity="1174"/>
                            <sld:ColorMapEntry color="#711e06" label="1192" opacity="1.0" quantity="1192"/>
                            <sld:ColorMapEntry color="#6f2007" label="1218" opacity="1.0" quantity="1218"/>
                            <sld:ColorMapEntry color="#6e2208" label="1236" opacity="1.0" quantity="1236"/>
                            <sld:ColorMapEntry color="#6e2308" label="1254" opacity="1.0" quantity="1254"/>
                            <sld:ColorMapEntry color="#6d2508" label="1272" opacity="1.0" quantity="1272"/>
                            <sld:ColorMapEntry color="#6c2709" label="1299" opacity="1.0" quantity="1299"/>
                            <sld:ColorMapEntry color="#6c280a" label="1316" opacity="1.0" quantity="1316"/>
                            <sld:ColorMapEntry color="#6c290a" label="1343" opacity="1.0" quantity="1343"/>
                            <sld:ColorMapEntry color="#6b2b0a" label="1361" opacity="1.0" quantity="1361"/>
                            <sld:ColorMapEntry color="#6a2c0b" label="1388" opacity="1.0" quantity="1388"/>
                            <sld:ColorMapEntry color="#6a2d0c" label="1406" opacity="1.0" quantity="1406"/>
                            <sld:ColorMapEntry color="#6b2f0d" label="1432" opacity="1.0" quantity="1432"/>
                            <sld:ColorMapEntry color="#6d3311" label="1468" opacity="1.0" quantity="1468"/>
                            <sld:ColorMapEntry color="#703715" label="1495" opacity="1.0" quantity="1495"/>
                            <sld:ColorMapEntry color="#733c1a" label="1530" opacity="1.0" quantity="1530"/>
                            <sld:ColorMapEntry color="#75411f" label="1566" opacity="1.0" quantity="1566"/>
                            <sld:ColorMapEntry color="#784523" label="1602" opacity="1.0" quantity="1602"/>
                            <sld:ColorMapEntry color="#7c4929" label="1646" opacity="1.0" quantity="1646"/>
                            <sld:ColorMapEntry color="#7f4e30" label="1691" opacity="1.0" quantity="1691"/>
                            <sld:ColorMapEntry color="#825436" label="1744" opacity="1.0" quantity="1744"/>
                            <sld:ColorMapEntry color="#86593d" label="1798" opacity="1.0" quantity="1798"/>
                            <sld:ColorMapEntry color="#895f44" label="1851" opacity="1.0" quantity="1851"/>
                            <sld:ColorMapEntry color="#8c644a" label="1913" opacity="1.0" quantity="1913"/>
                            <sld:ColorMapEntry color="#8f6952" label="1985" opacity="1.0" quantity="1985"/>
                            <sld:ColorMapEntry color="#936e59" label="2056" opacity="1.0" quantity="2056"/>
                            <sld:ColorMapEntry color="#96735f" label="2136" opacity="1.0" quantity="2136"/>
                            <sld:ColorMapEntry color="#987966" label="2225" opacity="1.0" quantity="2225"/>
                            <sld:ColorMapEntry color="#9b806f" label="2332" opacity="1.0" quantity="2332"/>
                            <sld:ColorMapEntry color="#9e8677" label="2466" opacity="1.0" quantity="2466"/>
                            <sld:ColorMapEntry color="#a08c80" label="2608" opacity="1.0" quantity="2608"/>
                            <sld:ColorMapEntry color="#a3928a" label="2733" opacity="1.0" quantity="2733"/>
                            <sld:ColorMapEntry color="#a69992" label="2876" opacity="1.0" quantity="2876"/>
                            <sld:ColorMapEntry color="#a79f9b" label="3054" opacity="1.0" quantity="3054"/>
                            <sld:ColorMapEntry color="#aaa6a3" label="3232" opacity="1.0" quantity="3232"/>
                            <sld:ColorMapEntry color="#acacaa" label="3419" opacity="1.0" quantity="3419"/>
                            <sld:ColorMapEntry color="#aeaeae" label="3597" opacity="1.0" quantity="3597"/>
                            <sld:ColorMapEntry color="#b2b2b2" label="3775" opacity="1.0" quantity="3775"/>
                            <sld:ColorMapEntry color="#b5b5b5" label="3954" opacity="1.0" quantity="3954"/>
                            <sld:ColorMapEntry color="#b8b8b8" label="4123" opacity="1.0" quantity="4123"/>
                            <sld:ColorMapEntry color="#bcbcbc" label="4265" opacity="1.0" quantity="4265"/>
                            <sld:ColorMapEntry color="#c0c0c0" label="4390" opacity="1.0" quantity="4390"/>
                            <sld:ColorMapEntry color="#c4c4c4" label="4497" opacity="1.0" quantity="4497"/>
                            <sld:ColorMapEntry color="#c8c8c8" label="4586" opacity="1.0" quantity="4586"/>
                            <sld:ColorMapEntry color="#cccccc" label="4675" opacity="1.0" quantity="4675"/>
                            <sld:ColorMapEntry color="#d0ced0" label="4764" opacity="1.0" quantity="4764"/>
                            <sld:ColorMapEntry color="#d4d2d4" label="4844" opacity="1.0" quantity="4844"/>
                            <sld:ColorMapEntry color="#d8d6d8" label="4916" opacity="1.0" quantity="4916"/>
                            <sld:ColorMapEntry color="#dad8da" label="4987" opacity="1.0" quantity="4987"/>
                            <sld:ColorMapEntry color="#dddbdd" label="5058" opacity="1.0" quantity="5058"/>
                            <sld:ColorMapEntry color="#e1dfe1" label="5156" opacity="1.0" quantity="5156"/>
                            <sld:ColorMapEntry color="#e5e3e5" label="5281" opacity="1.0" quantity="5281"/>
                            <sld:ColorMapEntry color="#e9e7e9" label="5477" opacity="1.0" quantity="5477"/>
                            <sld:ColorMapEntry color="#ebe9eb" label="8747" opacity="1.0" quantity="8747"/>
                        </sld:ColorMap>
                    </sld:RasterSymbolizer>
                </sld:Rule>
            </sld:FeatureTypeStyle>
        </sld:UserStyle>
    </sld:UserLayer>
</sld:StyledLayerDescriptor>
